<?php
/**
 * Implementation of hook_permission().
 */
function mysearch_permission() {
    return array(
        'access mysearch' => array(
            'title' => 'Access My Search',
            'description' => 'Allows a user to access search results',
        )
    );
}

/**
 * Implementation of hook_menu().
 */
function mysearch_menu() {
    $items['mysearch/%'] = array(
        'title callback' => 'mysearch_title',
        'title arguments' => array(1),
        'page callback' => 'mysearch_searchpage',
        'page arguments' => array(1),
        'access arguments' => array('access mysearch'),
        'type' => MENU_SUGGESTED_ITEM,
    );

    return $items;
}

function mysearch_title($name) {
    return 'Search result by "' .$name.'"';
}

/**
 * Menu callback provides a simple list of nodes matching the
 * search term Example: hitting the URL:
 *   http://domain.com/mysearch/example
 * will return a list of links to nodes which have the word
 * example in them.
 */
function mysearch_searchpage($name) {

    $items = array();

    $query = db_select('field_data_body', 't');
    $query->fields('t', array('entity_id', 'body_value'));
    $query->fields('n', array('title'));
    $query->join('node', 'n', 'n.nid = t.entity_id');
    $query->condition('t.body_value', '%'.$name.'%', 'LIKE');
    $result = $query->execute();
    $result = $result->fetchAll();

    foreach ($result as $row) {
        $items[]  = l($row->title, 'node/' . $row->entity_id);
    }

    return render (theme('item_list', array('items' => $items)));
}